apiVersion: v1
kind: Pod
metadata:
  name: voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_result

      ports:
        - containerPort: 80
          name: result
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis