apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    app: vote

spec:
  containers:
    - name: vote
      image: dockersamples/examplevotingapp_result

      ports:
        - containerPort: 80
          name: vote